## Dataset: Age & Salary

In [1]:
import pandas as pd

data = {
    'Age': [18, 25, 30, 35, 40, 50, 60],
    'Salary': [20000, 30000, 40000, 60000, 80000, 100000, 120000]
}

df = pd.DataFrame(data)
df

   Age  Salary
0   18   20000
1   25   30000
2   30   40000
3   35   60000
4   40   80000
5   50  100000
6   60  120000

## 1. Standardization (Z-Score Scaling or Z-Score Normalization)

In [2]:
# Manual Standardization
# Formula: z = (x − μ) / σ

df_manual_std = (df - df.mean()) / df.std(ddof=0)
df_manual_std

        Age    Salary
0 -1.402827 -1.280598
1 -0.882081 -0.991431
2 -0.510119 -0.702264
3 -0.138157 -0.123929
4  0.233805  0.454406
5  0.977728  1.032740
6  1.721652  1.611075

In [3]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
df_std = pd.DataFrame(scaler.fit_transform(df), columns=df.columns)
df_std

        Age    Salary
0 -1.402827 -1.280598
1 -0.882081 -0.991431
2 -0.510119 -0.702264
3 -0.138157 -0.123929
4  0.233805  0.454406
5  0.977728  1.032740
6  1.721652  1.611075

## 2. Normalization (MinMax Scaling)

In [4]:
# Manual MinMax Scaling
# Formula: x′ = (x − x_min) / (x_max − x_min)
# Output range: 0 to 1


df_manual_mm = (df - df.min()) / (df.max() - df.min())
df_manual_mm

        Age  Salary
0  0.000000     0.0
1  0.166667     0.1
2  0.285714     0.2
3  0.404762     0.4
4  0.523810     0.6
5  0.761905     0.8
6  1.000000     1.0

In [5]:
from sklearn.preprocessing import MinMaxScaler

mm = MinMaxScaler()
df_mm = pd.DataFrame(mm.fit_transform(df), columns=df.columns)
df_mm

        Age  Salary
0  0.000000     0.0
1  0.166667     0.1
2  0.285714     0.2
3  0.404762     0.4
4  0.523810     0.6
5  0.761905     0.8
6  1.000000     1.0

## 3. MaxAbs Scaling

In [6]:
# Manual MaxAbs Scaling
# Formula: x′ = x / |x_max|
# Output range: -1 to 1

df_manual_ma = df / df.abs().max()
df_manual_ma

        Age    Salary
0  0.300000  0.166667
1  0.416667  0.250000
2  0.500000  0.333333
3  0.583333  0.500000
4  0.666667  0.666667
5  0.833333  0.833333
6  1.000000  1.000000

In [7]:
from sklearn.preprocessing import MaxAbsScaler

ma = MaxAbsScaler()
df_ma = pd.DataFrame(ma.fit_transform(df), columns=df.columns)
df_ma

        Age    Salary
0  0.300000  0.166667
1  0.416667  0.250000
2  0.500000  0.333333
3  0.583333  0.500000
4  0.666667  0.666667
5  0.833333  0.833333
6  1.000000  1.000000

## 4. Robust Scaling

In [8]:
# Manual Robust Scaling
# Formula: x′ = (x − median) / IQR
# Where, IQR = Q3 − Q1


Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
df_manual_rs = (df - df.median()) / IQR
df_manual_rs

        Age    Salary
0 -0.971429 -0.727273
1 -0.571429 -0.545455
2 -0.285714 -0.363636
3  0.000000  0.000000
4  0.285714  0.363636
5  0.857143  0.727273
6  1.428571  1.090909

In [9]:
from sklearn.preprocessing import RobustScaler

rs = RobustScaler()
df_rs = pd.DataFrame(rs.fit_transform(df), columns=df.columns)
df_rs

        Age    Salary
0 -0.971429 -0.727273
1 -0.571429 -0.545455
2 -0.285714 -0.363636
3  0.000000  0.000000
4  0.285714  0.363636
5  0.857143  0.727273
6  1.428571  1.090909

## Fro Reference:
1. Standardization: https://youtu.be/1Yw9sC0PNwY
2. Normalization, MinMaxScaling, MaxAbsScaling, RobustScaling: https://youtu.be/eBrGyuA2MIg

## When to Use Each Feature Scaling Technique:

*   **Standardization (Z-Score Scaling)**: Use this when your data looks like a bell curve (normal distribution) or when your machine learning model expects it (like Linear Regression). It's good for handling unusually high or low values (outliers) but can squeeze everything into a smaller range if those outliers are very extreme.

*   **Normalization (Min-Max Scaling)**: Choose this when you want all your features to fit into a specific range, usually between 0 and 1. It's good for preventing features with small differences from getting lost, but it can be easily affected by very high or low values, as they will set the new boundaries.

*   **MaxAbs Scaling**: This scales your data by dividing each value by its largest absolute value. It's best if your data is already centered around zero or if most of your data is zero (sparse data). It keeps the data's original center and doesn't change where the zeros are.

*   **Robust Scaling**: This is great for data that has many outliers. Instead of using the average and standard deviation (which outliers can mess up), it uses the middle value (median) and the spread of the middle 50% of the data (interquartile range). This makes it less sensitive to extreme values.

## Formulas for Feature Scaling Techniques:

*   **Standardization (Z-Score Scaling)**:
    
    `z = (x - μ) / σ`
    
    Where:
    *   `x` is the original feature value.
    *   `μ` (mu) is the mean of the feature.
    *   `σ` (sigma) is the standard deviation of the feature.

*   **Normalization (Min-Max Scaling)**:
    
    `x' = (x - x_min) / (x_max - x_min)`
    
    Where:
    *   `x` is the original feature value.
    *   `x_min` is the minimum value of the feature.
    *   `x_max` is the maximum value of the feature.

*   **MaxAbs Scaling**:
    
    `x' = x / |x_max|`
    
    Where:
    *   `x` is the original feature value.
    *   `|x_max|` is the maximum absolute value of the feature.

*   **Robust Scaling**:
    
    `x' = (x - median) / IQR`
    
    Where:
    *   `x` is the original feature value.
    *   `median` is the median of the feature.
    *   `IQR` (Interquartile Range) is `Q3 - Q1` (the difference between the 75th percentile and the 25th percentile).